# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bec40a228492dc94c2c6a4673ee2b0eda94a7ebe84948cf379e175ee128547f59943674e35a5317c8c3710d64317a409d98d1b444de57c59307ebbd316a53556
  devise_key: 2fac972f46a9a109778d2590ffa1939d035fe074c44ef8ae72eb67b68f200b21ee3b4922f7b1693311c8248b3130cb3f981c4130d96ce83513b0fe2c488f0f
  
  access_key_id: AKIAIJJTZJ4ACF4AHQCQ
  secret_code: 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
test:
  secret_key_base: e9947c6915639d2ffe7cc877638af2454cb6e829e5950ab469b82fb1b47427922f1613709ec510953772de862b0a7c0272a8984e8badb3bd5e5dae92f0455bed
  
  access_key_id: AKIAIJJTZJ4ACF4AHQCQ
  secret_code: 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
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_key: <%= ENV["DEVISE_KEY_BASE"] %>

  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_code: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

