# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

#To drop and recreate databse from command line, rake commands are used:
# 1. rake db:drop
# 2. rake db:create
# 3. rake db:migrate
# 4. rake db:seed

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
